public with sharing class Detail {
    public String cartons;
    public String pallets;
    public String qty;
    public  String weight;
    public String length;
    public String width;
    public  String height;
    public String freightclass;

    // public Detail (String cartons, String pallets, String qty, String weight, String length, String width, String height, String freightclass) {
    //     this.cartons = cartons;
    //     this.pallets = pallets;
    //     this.qty = qty;
    //     this.weight = weight;
    //     this.length = length;
    //     this.width = width;
    //     this.height = height;
    //     this.freightclass = freightclass;
    // }
}