public with sharing class Stop {
    public String city;
    public  String state;
    public String postal;
    public String country;
    public Details details;
    public Accessorials accessorials;

    // public Stop(String city, String state, String postal, String country, List<Details> details, List<Accessorials> accessorials){
    //     this.city = city;
    //     this.state = state;
    //     this.postal = postal;
    //     this.country = country;
    //     this.details = details;
    //     this.accessorials = accessorials;
    // }
}
